name: CI-build-and-push-image-for-dotnetapp

# Controls when the action will run.
on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  pull_request:
    branches: [ master ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push auth
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth:latest, ${{ secrets.DOCKERHUB_USERNAME }}/auth:${{ github.run_number }}
