name: CI-build-and-push-image-for-dotnetapp

# Controls when the action will run.
on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  pull_request:
    branches: [ master ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  workflow_dispatch:

jobs:
  docker:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        if: runner.os != 'Windows'
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Buildx on Windows
        if: runner.os == 'Windows'
        run: |
          Invoke-WebRequest -Uri https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.windows-amd64.zip -OutFile buildx.zip
          Expand-Archive -Path buildx.zip -DestinationPath .
          mkdir -p ~/.docker/cli-plugins
          Move-Item -Path ./buildx-v0.8.2.windows-amd64/docker-buildx.exe -Destination ~/.docker/cli-plugins/docker-buildx.exe
          docker buildx create --name builder
          docker buildx use builder
          docker buildx inspect --bootstrap

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push prm
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/prm:latest, ${{ secrets.DOCKERHUB_USERNAME }}/prm:${{ github.run_number }}
